global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']

# Read from our correctly extracted TSDB data
storage:
  tsdb:
    path: /prometheus/data_final
    retention.time: 365d